services:
  server:

    build: .
    depends_on:
      - db
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TOKEN_DURATION_HOURS=${TOKEN_DURATION_HOURS}

  db:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: