services:
  server:
    image: soldatova64/time-price-backend:latest
    build: .
    depends_on:
      - db
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - ENV=development
    volumes:
      - ./:/app
    command: go run main.go
  db:
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: