PUT http://localhost:8080/admin/user/17
Content-Type: application/json
Authorization: Bearer ba1cb34863f68ffe378d7471224f2ed0

{
  "password": "Qwerty123asd"
}

###
PUT http://localhost:8080/admin/user/1717171
Content-Type: application/json
Authorization: Bearer ba1cb34863f68ffe378d7471224f2ed0

{
  "password": "Qwerty123asd"
}

###
PUT http://localhost:8080/admin/user/17
Content-Type: application/json
Authorization: Bearer ba1cb34863f68ffe378d7471224f2ed0

{
  "password": "Qwerty123zxc"
}

###
PUT http://localhost:8080/admin/user/14
Content-Type: application/json
Authorization: Bearer ee0eba4a8d823c0cd9d9dc92e77c45f6

{
  "password": "Qwerty123ffg"
}

###
PUT http://localhost:8080/admin/user/14
Content-Type: application/json
Authorization: Bearer ee0eba4a8d823c0cd9d9dc92e77c45f6

{
  "password": ""
}

###
PUT http://localhost:8080/admin/user/14
Content-Type: application/json
Authorization: Bearer ee0eba4a8d823c0cd9d9dc92e77c45f6

{
}