POST http://localhost:8080/admin/user
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "Qwerty123ffg"
}

###
POST http://localhost:8080/admin/user
Content-Type: application/json

{
  "username": "",
  "email": "",
  "password": ""
}

###
POST http://localhost:8080/admin/user
Content-Type: application/json

{
  "username": "testuser",
  "email": "biektrnb",
  "password": "qwerty123"
}

###
POST http://localhost:8080/admin/user
Content-Type: application/json

{
  "username": "",
  "email": "test@example.com",
  "password": "qwerty123"
}

###
POST http://localhost:8080/admin/user
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": ""
}
