POST http://localhost:8080/admin/expense
Content-Type: application/json
Authorization: Bearer ad6ce4a9c0d5f660e431fd360530e94c

{
    "thing_id": 44,
    "sum": 50000,
    "description": "ремонт",
    "expense_date": "2025-05-05T00:00:00Z"
}

###

POST http://localhost:8080/admin/expense
Content-Type: application/json
Authorization: Bearer adb6e7fa3cc3ec21c41de2f427e7bdc9

{
    "thing_id": 2,
    "sum": 100,
    "description": "ремонт",
    "expense_date": "2025-05-05T00:00:00Z"
}

###

POST http://localhost:8080/admin/expense

{
    "thing_id": 2,
    "sum": 5000,
    "description": null,
    "expense_date": "2025-05-05T00:00:00Z"
}

###

POST http://localhost:8080/admin/expense

{
    "thing_id": 1,
    "sum": 5000,
    "description": "ремонт",
    "expense_date": null
}

###

POST http://localhost:8080/admin/expense

{
    "thing_id": 23,
    "sum": 4000,
    "description": "ремонт",
    "expense_date": "2025-05-05T00:00:00Z"
}

