POST http://localhost:8080/admin/thing
Content-Type: application/json
Authorization: Bearer a33962f9e14a3389f38f365daf61549d

{
    "name": "вещь1",
    "pay_date": "2025-01-01T00:00:00+03:00",
    "pay_price": 1000,
    "sale_date": "2025-01-02T00:00:00+03:00",
    "sale_price": 900
}

###

POST http://localhost:8080/admin/thing
Content-Type: application/json
Authorization: Bearer adb6e7fa3cc3ec21c41de2f427e7bdc9

{
    "name": "вещь2",
    "pay_date": "2025-01-01T00:00:00Z",
    "pay_price": 2000,
    "sale_date": "2025-05-05T00:00:00Z",
    "sale_price": 1800
}

###

POST http://localhost:8080/admin/thing

{
    "name": "вещь3",
    "pay_date": "2025-01-01T00:00:00Z",
    "pay_price": 0,
    "sale_date": "2025-01-02T00:00:00Z",
    "sale_price": 900
}

###

POST http://localhost:8080/admin/thing

{
    "name": "вещь4",
    "pay_date": "2026-01-01T00:00:00Z",
    "pay_price": 3333,
    "sale_date": "2025-01-02T00:00:00Z",
    "sale_price": 900
}

###

POST http://localhost:8080/admin/thing

{
    "name": "вещь5",
    "pay_date": "2024-01-01T00:00:00Z",
    "pay_price": 3333,
    "sale_date": null,
    "sale_price": 999
}

###

POST http://localhost:8080/admin/thing

{
    "name": "вещь6",
    "pay_date": "2024-01-01T00:00:00Z",
    "pay_price": 3333,
    "sale_date": "2025-01-02T00:00:00Z",
    "sale_price": null
}

###

POST http://localhost:8080/admin/thing

{
    "name": "вещь7",
    "pay_date": "2024-01-01T00:00:00Z",
    "pay_price": 500000,
    "sale_date": null,
    "sale_price": null
}