PUT http://localhost/admin/thing/1

{
    "name": "обновленная вещь1",
    "pay_date": "2025-01-01T00:00:00+03:00",
    "pay_price": 1000,
    "sale_date": "2025-01-02T00:00:00+03:00",
    "sale_price": 500
}

###

PUT http://localhost/admin/thing/2

{
    "name": "обновленная вещь2",
    "pay_date": "2025-01-01T00:00:00Z",
    "pay_price": 2000,
    "sale_date": "2025-05-11T00:00:00Z",
    "sale_price": 1800
}

###

PUT http://localhost/admin/thing/2

{
    "name": "обновленная вещь3"
}