PUT http://localhost:8080/admin/thing/1
Content-Type: application/json
Authorization: a33962f9e14a3389f38f365daf61549d

{
    "name": "обновленная вещь1",
    "pay_date": "2025-01-01T00:00:00+03:00",
    "pay_price": 1000,
    "sale_date": "2025-01-02T00:00:00+03:00",
    "sale_price": 500
}

###

PUT http://localhost:8080/admin/thing/2

{
    "name": "обновленная вещь2",
    "pay_date": "2025-01-01T00:00:00Z",
    "pay_price": 2000,
    "sale_date": "2025-05-11T00:00:00Z",
    "sale_price": 1800
}

###

PUT http://localhost:8080/admin/thing/2

{
    "name": "обновленная вещь3"
}

###

PUT http://localhost:8080/admin/thing/2

{
    "sale_date": "2025-03-03T00:00:00Z"
}

###

PUT http://localhost:8080/admin/thing/2

{
    "pay_price": 1999
}
