POST http://localhost:8080/admin/user
Content-Type: application/json
Authorization: Bearer a33962f9e14a3389f38f365daf61549d

{
  "username": "anna1",
  "email": "test@example.com",
  "password": "Qwerty123ffg"
}

###
POST http://localhost:8080/admin/user
Content-Type: application/json

{
  "username": "",
  "email": "",
  "password": ""
}

###
POST http://localhost:8080/admin/user
Content-Type: application/json

{
  "username": "anna1",
  "email": "biektrnb",
  "password": "Qwerty123ffg"
}

###
POST http://localhost:8080/admin/user
Content-Type: application/json

{
  "username": "",
  "email": "test@example.com",
  "password": "Qwerty123ffg"
}

###
POST http://localhost:8080/admin/user
Content-Type: application/json

{
  "username": "anna1",
  "email": "test@example.com",
  "password": ""
}
