POST http://localhost:8080/auth
Content-Type: application/json

{
  "username": "testuser",
  "password": "Qwerty123ffg"
}

###
POST http://localhost:8080/auth
Content-Type: application/json

{
  "username": "",
  "password": ""
}

###
OPTIONS http://localhost/auth