POST http://localhost/auth
Content-Type: application/json

{
  "username": "testuser",
  "password": "qwerty123ffg"
}

###
POST http://localhost/auth
Content-Type: application/json

{
  "username": "anna",
  "password": "anna1234"
}


###
POST http://localhost/auth
Content-Type: application/json

{
  "username": "",
  "password": ""
}

###
OPTIONS http://localhost/auth